spring:
  sql:
    init:
      mode: always
  h2:
    console:
      enabled: true
  jpa:
    defer-datasource-initialization: true
    show-sql: true
    properties:
      hibernate:
        ddl-auto: none
        format_sql: true
